---
title: "Week 13 Class Average"
author: "Zhenyu Li"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    number_sections: false
    theme: paper
    highlight: zenburn
    fig_caption: true
    keep_md: false
    df_print: kable
    self_contained: true
    fig_dpi: 300
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
setwd(getwd())
Sys.setenv(TZ = "Asia/Shanghai")
library(readxl)
library(lubridate)
library(tidyverse)
library(writexl)
library(openxlsx)
library(modelsummary)
library(tidyplots)
options(scipen = 999)

mytheme <- theme(
    panel.grid.major.y = element_line(color = "gray90"),
    panel.grid.major.x =  element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(color = "black"),  # 设置坐标轴线
    axis.text.x = element_text(angle = 45, hjust = 1, size = 9),
    axis.text.y = element_text(size = 10),
    axis.title = element_text(size = 12, face = "bold"),
    plot.title = element_text(size = 14, face = "bold", hjust = 0.5)
  )

```

```{r read data, echo=FALSE, include=FALSE}
# df0 = read_excel("《睡眠与健康》睡眠日志raw-第一批.xlsx")

# 第二批
df0 = read_excel("《睡眠与健康》课程追踪问卷.xlsx")

df = df0

# 修正日期错误
df = df %>% 
  mutate(
    date_of_today = case_when(
      序号 == "25" ~ "2025-03-08",
      序号 == "85" ~ "2025-03-26",
      序号 == "113" ~ "2025-04-06",
      序号 == "187" ~ "2025-05-14",
      TRUE ~ date_of_today
    ),
    bed_time = case_when(
      序号 == "31" ~ "2025-03-08 00:30:34",
      序号 == "35" ~ "2025-03-08 01:47:00",
      序号 == "56" ~ "2025-03-15 00:30:33",
      TRUE ~ bed_time
    ),
    prepare_to_sleep_time = case_when(
      序号 == "2" ~ "02:00:34",
      序号 == "168" ~ "03:07:48",
      TRUE ~ prepare_to_sleep_time
    ),
  ) %>% 
  # 入睡时间填写过于极端（超过凌晨四点，且躺在床上时间和入睡时间差距过大）
  filter(
    序号 != "70" & 序号 != "118"
  ) 

df$prepare_to_sleep_time = paste0(df$date_of_today, " ", df$prepare_to_sleep_time)

# 将字符型时间转换为 POSIXct 格式
df$bed_time = as.POSIXct(df$bed_time, format = "%Y-%m-%d %H:%M:%S")
```

上床时间清理

```{r data cleaning-bedtime}
df$prepare_to_sleep_time = as.POSIXct(df$prepare_to_sleep_time, format = "%Y-%m-%d %H:%M:%S")

# 创建 date_of_today 的凌晨 00:00 时间戳
df$date_of_today_midnight = as.POSIXct(paste0(as.Date(df$date_of_today), " 00:00:00"), 
                                       format = "%Y-%m-%d %H:%M:%S")

# 计算时间差（单位：分钟）

# 上床时间和当天日期的差值，差异应在 ±12 小时内
df$bed_from_midnight_mins = as.numeric(difftime(df$bed_time, df$date_of_today_midnight, units = "mins"))

# 准备睡觉时间与当天凌晨的差值，用于检查是否在 ±12 小时内
df$prepare_from_midnight_mins = as.numeric(difftime(df$prepare_to_sleep_time, df$date_of_today_midnight, units = "mins"))

# 准备睡觉时间与上床时间的差值，预期为正（prepare_to_sleep_time > bed_time）
df$prepare_minus_bed_mins = as.numeric(difftime(df$prepare_to_sleep_time, df$bed_time, units = "mins"))


# 修正时间数据
df = df %>% 
  mutate(
    # 分情况修正 bed_time 和 prepare_to_sleep_time
    
    bed_time_revise = case_when(
      
      bed_from_midnight_mins < -1080 & bed_from_midnight_mins >= -1440 ~ bed_time + hours(24),  # 如果显示是前一天凌晨0-6点之间睡的，认为是日期填错了一天，但是时制填对了，所以加24小时
      
      bed_from_midnight_mins < -660 & bed_from_midnight_mins >= -1080 ~ bed_time + hours(12),  # 如果显示是前一天早上6点到中午13点之点睡的，认为是日期填对了，但是把24小时制的时间当成12小时制的时间，所以加12小时
      bed_from_midnight_mins > 360 & bed_from_midnight_mins <= 780 ~ bed_time - hours(12),  # 如果显示是当天早上6点到中午13点之间睡的，认为是把日期和时制都填错了，所以减去12小时
      bed_from_midnight_mins > 1080 & bed_from_midnight_mins < 1440 ~ bed_time - hours(24),  # 如果显示是当天下午6点之后睡的，认为是日期填错了，但是时制填对了，所以减去24小时
      
      bed_from_midnight_mins > 1440 | bed_from_midnight_mins < -1440 ~ NA,  # 如果bed_time早于前一天的凌晨6点，或者超过当天24点，可能是日期差距太大，需要手动检查
      
      TRUE ~ bed_time  # 其他情况保持不变
    ),
    
    prepare_to_sleep_time_revise = case_when(
      
       prepare_from_midnight_mins < -1080 & prepare_from_midnight_mins >= -1440 ~ prepare_to_sleep_time + hours(24),  # 如果显示是前一天凌晨0-6点之间睡的，认为是日期填错了一天，但是时制填对了，所以加24小时
      
      prepare_from_midnight_mins < -660 & prepare_from_midnight_mins >= -1080 ~ prepare_to_sleep_time + hours(12), # 如果显示是前一天早上6点到中午13点之点睡的，认为是日期填对了，但是把24小时制的时间当成12小时制的时间，所以加12小时
      prepare_from_midnight_mins > 360 & prepare_from_midnight_mins <= 780 ~ prepare_to_sleep_time - hours(12),  # 如果显示是当天早上6点到中午13点之间睡的，认为是把日期和时制都填错了，所以减去12小时
      prepare_from_midnight_mins > 1080 & prepare_from_midnight_mins < 1440 ~ prepare_to_sleep_time - hours(24),  # 如果显示是当天下午6点之后睡的，认为是日期填错了，但是时制填对了，所以减去24小时
      
      prepare_from_midnight_mins > 1440 | prepare_from_midnight_mins < -1440 ~ NA,  # 如果prepare_to_sleep_time早于前一天的凌晨0点，或者超过当天24点，可能是日期差距太大，需要手动检查
      
      TRUE ~ prepare_to_sleep_time
    ),

    bed_revised_flag = if_else(bed_time_revise != bed_time, 1, 0),
    prepare_revised_flag = if_else(prepare_to_sleep_time_revise != prepare_to_sleep_time, 1, 0),
    bed_wrong_flag = if_else(difftime(prepare_to_sleep_time_revise, bed_time_revise)<0, 1, 0),
  )


# 如果prepare_to_sleep_time_revise早于bed_time_revise，交换这两个时间
df = df %>% 
  mutate(
    prepare_to_sleep_time_revise = if_else(bed_wrong_flag == 1, bed_time_revise, prepare_to_sleep_time_revise),
    bed_time_revise = if_else(bed_wrong_flag == 1, prepare_to_sleep_time_revise, bed_time_revise)
  )
# 打印有多少行数据是prepare_to_sleep_time_revise早于bed_time_revise
# print(nrow(df %>% filter(bed_wrong_flag == 1)))




term_start = "2025-02-10"

df_organized = df %>% 
  rename(
    No = 序号,
    sleep_latency = `sleep latency`
  ) %>% 
  select(
    No, date_of_today, date_of_today_midnight,
    bed_time_revise, prepare_to_sleep_time_revise, sleep_latency,
    total_sleep_time_hour, total_sleep_time_min,
    bed_time, prepare_to_sleep_time
  ) %>% 
  mutate(
    clean_bed_time = as.numeric(difftime(bed_time_revise, date_of_today_midnight, units = "hours") + 24),
    
    clean_prepare_to_sleep_time = as.numeric(difftime(prepare_to_sleep_time_revise, date_of_today_midnight, units = "hours") + 24),
    
    sleep_onset = clean_prepare_to_sleep_time + sleep_latency/60,
    
    total_sleep_time = as.numeric(total_sleep_time_hour) + as.numeric(total_sleep_time_min)/60,
    
    night_procrastination_time = clean_prepare_to_sleep_time - clean_bed_time,
    
    wake_up_time = sleep_onset + total_sleep_time - 24,
    
    date_of_today = as.Date(date_of_today),
    
    date_of_today_midnight = as.Date(date_of_today_midnight),
    
    weekday = weekdays(date_of_today),
    weekend = if_else(weekday %in% c("星期六", "星期日"), "Weekend", "Weekday"),
    term_week = difftime(date_of_today, as.Date(term_start), tz = "Asia/Shanghai", units = "weeks"),
    term_week_2 = case_when(
      weekend == "Weekend" ~ floor(as.numeric(term_week)) + 0.8,
      weekend == "Weekday" ~ floor(as.numeric(term_week)) + 0.2,
      TRUE ~ floor(as.numeric(term_week))
    )
  )

# 睡眠时长分组和时型分组
df_organized = df_organized %>%
  mutate(
    total_sleep_time_group = case_when(
      total_sleep_time < 6 ~ "<6",
      total_sleep_time >= 6 & total_sleep_time < 7 ~ "[6-7)",
      total_sleep_time >= 7 & total_sleep_time < 9 ~ "[7-9)",
      total_sleep_time >= 9 ~ ">9",
      TRUE ~ NA_character_
    ),
    chronotype = case_when(
      clean_prepare_to_sleep_time < 23 ~ "<23",
      clean_prepare_to_sleep_time >= 23 & clean_prepare_to_sleep_time < 24 ~ "[23-24)",
      clean_prepare_to_sleep_time >= 24 & clean_prepare_to_sleep_time < 25 ~ "[24-25)",
      clean_prepare_to_sleep_time >= 25 & clean_prepare_to_sleep_time < 26 ~ "[25-26)",
      clean_prepare_to_sleep_time >= 26 ~ ">26",
      TRUE ~ NA_character_
    )
  )





#     # 标识是周几
# df$date_of_today = as.Date(df$date_of_today)
# df$weekday = weekdays(df$date_of_today)
# 
# # 标识是否是周末
# df$weekend = if_else(df$weekday %in% c("星期六", "星期日"), "Weekend", "Weekday")
```

# 描述性统计
```{r 总体描述性统计, warnings=FALSE}
datasummary_skim(df_organized %>% select(-No, -date_of_today, -date_of_today_midnight,-total_sleep_time_hour,-total_sleep_time_min))

```

```{r 分组描述性统计, warnings=FALSE}
library(table1)
pvalue <- function(x, ...) {
    # Construct vectors of data y, and groups (strata) g
    y <- unlist(x)
    g <- factor(rep(1:length(x), times=sapply(x, length)))
    if (is.numeric(y)) {
        # For numeric variables, perform a standard 2-sample t-test
        p <- t.test(y ~ g)$p.value
    } else {
        # For categorical variables, perform a chi-squared test of independence
        p <- chisq.test(table(y, g))$p.value
    }
    # Format the p-value, using an HTML entity for the less-than sign.
    # The initial empty string places the output on the line below the variable label.
    c("", sub("<", "&lt;", format.pval(p, digits=3, eps=0.001)))
}

my.render.cat <- function(x) {
    # 计算分类变量的默认统计数据
    stats <- stats.default(x)
    # 对每个类别的统计数据进行格式化
    formatted_stats <- lapply(stats, function(y) {
        with(y, {
            # 为 FREQ 添加千分位分隔符
            freq_formatted <- format(FREQ, big.mark = ",")
            # 将 PCT 格式化为整数并添加百分号
            pct_formatted <- sprintf("%.2f%%", PCT)
            # 组合成 "频率 (百分比)" 的格式
            sprintf("%s (%s)", freq_formatted, pct_formatted)
        })
    })
    # 返回格式化后的结果向量
    c("", formatted_stats)
}
footnote_text <- "Note: The p-values are calculated by chi-square test for categorical variables. Column percentages are presented in paratheses. "
# 按周中和周末分组

df_table1 = df_organized

df_table1 = df_table1 %>% 
  mutate(
    weekend = factor(weekend, levels = c("Weekday", "Weekend")),
    total_sleep_time_group = factor(total_sleep_time_group, levels = c("<6", "[6-7)", "[7-9)", ">9")),
    chronotype = factor(chronotype, levels = c("<23", "[23-24)", "[24-25)", "[25-26)", ">26"))
  )

label(df_table1$weekend) <- "Weekend"
label(df_table1$total_sleep_time_group) <- "Total sleep time group"
label(df_table1$chronotype) <- "Chronotype"
label(df_table1$clean_bed_time) <- "Bed time"
label(df_table1$clean_prepare_to_sleep_time) <- "Prepare to sleep time"
label(df_table1$sleep_latency) <- "Sleep latency"
label(df_table1$night_procrastination_time) <- "Night procrastination time"
label(df_table1$wake_up_time) <- "Wake up time"
label(df_table1$total_sleep_time) <- "Total sleep time"
label(df_table1$term_week_2) <- "Term week"





table1(~ total_sleep_time + clean_bed_time + clean_prepare_to_sleep_time + 
         sleep_latency + night_procrastination_time + wake_up_time + 
         total_sleep_time_group + chronotype| weekend,
       data = df_table1, 
       overall = FALSE, 
       extra.col = list(`P-value` = pvalue),
       topclass = "Rtable1-zebra",
       render.categorical = my.render.cat,
       caption = "Descriptive statistics of sleep variables by weekend and weekday",
       footnote = footnote_text )


# df_figure4$h_overweight <- factor(df_figure4$h_overweight)
# df_figure4$h_obese <- factor(df_figure4$h_obese)
# df_figure4$h_normal <- factor(df_figure4$h_normal)
# df_figure4$h_underweight <- factor(df_figure4$h_underweight)
# df_figure4$w_overweight <- factor(df_figure4$w_overweight)
# df_figure4$w_obese <- factor(df_figure4$w_obese)
# df_figure4$w_normal <- factor(df_figure4$w_normal)
# df_figure4$w_underweight <- factor(df_figure4$w_underweight)
# 
# label(df_figure4$h_overweight) <- "Husband overweight"
# label(df_figure4$h_obese) <- "Husband obese"
# label(df_figure4$h_normal) <- "Husband normal"
# label(df_figure4$h_underweight) <- "Husband underweight"
# label(df_figure4$w_overweight) <- "Wife overweight"
# label(df_figure4$w_obese) <- "Wife obese"
# label(df_figure4$w_normal) <- "Wife normal"
# label(df_figure4$w_underweight) <- "Wife underweight"


# table1(~ h_underweight +  h_normal + h_overweight + h_obese + 
#          w_underweight +  w_normal + w_overweight + w_obese | edu_assor5,
#        data = df_figure4, 
#        overall = FALSE, 
#        extra.col = list(`P-value` = pvalue),
#        # topclass = "Rtable1-zebra",
#        render.categorical = my.render.cat,
#        caption = "Descriptive statistics of gendered education gradient of BMI at couple level: full sample",
#        footnote = footnote_text )



```

# 各项指标随时间变化画图


## 睡眠时长

```{r plot sleep duration}
# 横轴是日期，纵轴是睡眠时间，画出折线图，把平均睡眠时间和标准差画在一起
temp = df_organized %>% 
  select(term_week_2, total_sleep_time,weekend) %>% 
  group_by(term_week_2) %>% 
  reframe(
    weekend = first(weekend),
    mean_value = mean(total_sleep_time, na.rm = TRUE),
    sd_value = sd(total_sleep_time, na.rm = TRUE),  # 计算标准差
    obs = n() # 计算样本量
  ) 

a = ggplot(data = temp, aes(x = term_week_2, y = mean_value)) +
  
  # 添加标准差阴影（误差带）
  geom_ribbon(aes(ymin = mean_value - sd_value, ymax = mean_value + sd_value), 
              alpha = 0.2, color = NA) +
  
  # 画出均值折线
  geom_line(linewidth = 1.5, alpha = 0.8) +
  
  # 画出均值点
  geom_point(aes(size = obs, color = weekend), alpha = 0.8) +
  
  labs(title = "睡眠时间均值随日期变化", x = "周数", y = "小时") +
  
  # x轴连续格式
  scale_x_continuous(
    breaks = seq(3, 17, 0.5),
    limits = c(3, 15)
  ) +

  
  theme_minimal() +
  
  mytheme

plotly::ggplotly(a)

```


## 上床时间点

```{r plot bed time}
# 横轴是日期，纵轴是上床时间，画出折线图，把平均上床时间和标准差画在一起
temp = df_organized %>% 
  select(term_week_2, clean_bed_time, weekend) %>% 
  group_by(term_week_2) %>% 
  reframe(
    weekend = first(weekend),
    mean_value = mean(clean_bed_time, na.rm = TRUE),
    sd_value = sd(clean_bed_time, na.rm = TRUE),  # 计算标准差
    obs = n() # 计算样本量
  )

a = ggplot(data = temp, aes(x = term_week_2, y = mean_value)) +
  
  # 添加标准差阴影（误差带）
  geom_ribbon(aes(ymin = mean_value - sd_value, ymax = mean_value + sd_value), 
              alpha = 0.2, color = NA) +
  
  # 画出均值折线
  geom_line(linewidth = 1.5, alpha = 0.8) +
  
  # 画出均值点
  geom_point(aes(size = obs, color = weekend), alpha = 0.8) +
  
  labs(title = "上床时间均值随日期变化", x = "周数", y = "小时") +
  
  # x轴连续格式
  scale_x_continuous(
    breaks = seq(3, 17, 0.5),
    limits = c(3, 15)
  ) +
  
  theme_minimal() +
  
  mytheme

plotly::ggplotly(a)

```

## 准备睡觉时间点
```{r plot prepare to sleep time}
# 横轴是日期，纵轴是准备睡觉时间，画出折线图，把平均准备睡觉时间和标准差画在一起
temp = df_organized %>% 
  select(term_week_2, clean_prepare_to_sleep_time, weekend) %>% 
  group_by(term_week_2) %>% 
  reframe(
    weekend = first(weekend),
    mean_value = mean(clean_prepare_to_sleep_time, na.rm = TRUE),
    sd_value = sd(clean_prepare_to_sleep_time, na.rm = TRUE),  # 计算标准差
    obs = n() # 计算样本量
  )


a = ggplot(data = temp, aes(x = term_week_2, y = mean_value)) +
  
  # 添加标准差阴影（误差带）
  geom_ribbon(aes(ymin = mean_value - sd_value, ymax = mean_value + sd_value), 
              alpha = 0.2, color = NA) +
  
  # 画出均值折线
  geom_line(linewidth = 1.5, alpha = 0.8) +
  
  # 画出均值点
  geom_point(aes(size = obs, color = weekend), alpha = 0.8) +
  
  labs(title = "准备睡觉时间均值随日期变化", x = "周数", y = "小时") +
  
  # x轴连续格式
  scale_x_continuous(
    breaks = seq(3, 17, 0.5),
    limits = c(3, 15)
  ) +
  
  theme_minimal() +
  
  mytheme

plotly::ggplotly(a)

```

## 起床时间点
```{r plot wake up time}
# 横轴是日期，纵轴是起床时间，画出折线图，把平均起床时间和标准差画在一起
temp = df_organized %>% 
  select(term_week_2, wake_up_time, weekend) %>% 
  group_by(term_week_2) %>% 
  reframe(
    weekend = first(weekend),
    mean_value = mean(wake_up_time, na.rm = TRUE),
    sd_value = sd(wake_up_time, na.rm = TRUE),  # 计算标准差
    obs = n() # 计算样本量
  )

a = ggplot(data = temp, aes(x = term_week_2, y = mean_value)) +
  
  # 添加标准差阴影（误差带）
  geom_ribbon(aes(ymin = mean_value - sd_value, ymax = mean_value + sd_value), 
              alpha = 0.2, color = NA) +
  
  # 画出均值折线
  geom_line(linewidth = 1.5, alpha = 0.8) +
  
  # 画出均值点
  geom_point(aes(size = obs, color = weekend), alpha = 0.8) +
  
  labs(title = "起床时间均值随日期变化", x = "周数", y = "小时") +
  
  # x轴连续格式
  scale_x_continuous(
    breaks = seq(3, 17, 0.5),
    limits = c(3, 15)
  ) +
  
  theme_minimal() +
  
  mytheme


plotly::ggplotly(a)

```

## 睡眠潜伏期
```{r plot sleep latency}
# 横轴是日期，纵轴是睡眠潜伏期，画出折线图，把平均睡眠潜伏期和标准差画在一起
temp = df_organized %>% 
  select(term_week_2, sleep_latency, weekend) %>% 
  group_by(term_week_2) %>% 
  reframe(
    weekend = first(weekend),
    mean_value = mean(sleep_latency, na.rm = TRUE),
    sd_value = sd(sleep_latency, na.rm = TRUE),  # 计算标准差
    obs = n() # 计算样本量
  )

a = ggplot(data = temp, aes(x = term_week_2, y = mean_value)) +
  
  # 添加标准差阴影（误差带）
  geom_ribbon(aes(ymin = mean_value - sd_value, ymax = mean_value + sd_value), 
              alpha = 0.2, color = NA) +
  
  # 画出均值折线
  geom_line(linewidth = 1.5, alpha = 0.8) +
  
  # 画出均值点
  geom_point(aes(size = obs, color = weekend), alpha = 0.8) +
  
  labs(title = "睡眠潜伏期均值随日期变化", x = "周数", y = "分钟") +
  
  # x轴连续格式
  scale_x_continuous(
    breaks = seq(3, 17, 0.5),
    limits = c(3, 15)
  ) +
  
  theme_minimal() +
  
  mytheme

plotly::ggplotly(a)

```


## 睡眠拖延
```{r plot sleep procrastination}
# 横轴是日期，纵轴是睡眠拖延时间，画出折线图，把平均睡眠拖延时间和标准差画在一起
temp = df_organized %>% 
  select(term_week_2, night_procrastination_time, weekend) %>% 
  group_by(term_week_2) %>% 
  reframe(
    weekend = first(weekend),
    mean_value = mean(night_procrastination_time*60, na.rm = TRUE),
    sd_value = sd(night_procrastination_time*60, na.rm = TRUE),  # 计算标准差
    obs = n() # 计算样本量
  )

a = ggplot(data = temp, aes(x = term_week_2, y = mean_value)) +
  
  # 添加标准差阴影（误差带）
  geom_ribbon(aes(ymin = mean_value - sd_value, ymax = mean_value + sd_value), 
              alpha = 0.2, color = NA) +
  
  # 画出均值折线
  geom_line(linewidth = 1.5, alpha = 0.8) +
  
  # 画出均值点
  geom_point(aes(size = obs, color = weekend), alpha = 0.8) +
  
  labs(title = "睡眠拖延时间均值随日期变化", x = "周数", y = "分钟") +
  
  # x轴连续格式
  scale_x_continuous(
    breaks = seq(3, 17, 0.5),
    limits = c(3, 15)
  ) +
  
  theme_minimal() +
  
  mytheme


plotly::ggplotly(a)

```


# 各项指标周中周末对比

```{r 周中周末对比,eval = FALSE}
# 横轴是各项指标，纵轴是均值，分组变量是周中和周末，画出箱线图，添加显著性标记

# 使用tidyplots包

# 把df_organized转换成长格式，生成一个group变量，储存各项指标的名称，生成一个weekend变量，标识是周中还是周末，然后生成一个value变量，储存各项指标根据值，sd变量储存各项指标的标准差
library(tidyplots)

# 总睡眠时长
p_tst_2 = df_organized |>
  tidyplot(x = weekend, y = total_sleep_time) |>
  add_boxplot() |>
  add_data_points() |>
  add_test_asterisks(hide_info = TRUE, hide.ns = F) |>
  adjust_x_axis(title = "") |>
  adjust_y_axis(title = "总睡眠时长") |>
  add_title("周中周末与总睡眠时长的关系") %>% 
  adjust_size(width = 100, height = 80)


# 上床时间
p_bedtime_2 = df_organized |>
  tidyplot(x = weekend, y = clean_bed_time) |>
  add_boxplot() |>
  add_data_points() |>
  add_test_asterisks(hide_info = TRUE, hide.ns = F) |>
  adjust_x_axis(title = "") |>
  adjust_y_axis(title = "上床时间") |>
  add_title("周中周末与上床时间的关系") %>% 
  adjust_size(width = 100, height = 80)

# 准备睡觉时间
p_prepare_2 = df_organized %>% filter(clean_prepare_to_sleep_time<28) |>
  tidyplot(x = weekend, y = clean_prepare_to_sleep_time) |>
  add_boxplot() |>
  add_data_points() |>
  add_test_asterisks(hide_info = TRUE, hide.ns = F) |>
  adjust_x_axis(title = "") |>
  adjust_y_axis(title = "准备睡觉时间") |>
  add_title("周中周末与准备睡觉时间的关系") %>% 
  adjust_size(width = 100, height = 80)

# 起床时间
p_wake_2 = df_organized |>
  tidyplot(x = weekend, y = wake_up_time) |>
  add_boxplot() |>
  add_data_points() |>
  add_test_asterisks(hide_info = TRUE, hide.ns = F) |>
  adjust_x_axis(title = "") |>
  adjust_y_axis(title = "起床时间") |>
  add_title("周中周末与起床时间的关系") %>% 
  adjust_size(width = 100, height = 80)

# 睡眠潜伏期
p_latency_2 = df_organized %>% filter(sleep_latency < 60) |>
  tidyplot(x = weekend, y = sleep_latency) |>
  add_boxplot() |>
  add_data_points() |>
  add_test_asterisks(hide_info = T, hide.ns = F) |>
  adjust_x_axis(title = "") |>
  adjust_y_axis(title = "睡眠潜伏期") |>
  add_title("周中周末与睡眠潜伏期的关系") %>% 
  adjust_size(width = 100, height = 80)

# 睡眠拖延
p_procrastination_2 = df_organized %>% filter(night_procrastination_time < 2) |>
  mutate(night_procrastination_time = night_procrastination_time * 60) |>
  tidyplot(x = weekend, y = night_procrastination_time) |>
  add_boxplot() |>
  add_data_points() |>
  add_test_asterisks(hide_info = T, hide.ns = F) |>
  adjust_x_axis(title = "") |>
  adjust_y_axis(title = "睡眠拖延时间") |>
  add_title("周中周末与睡眠拖延时间的关系") %>% 
  adjust_size(width = 100, height = 80)

```

```{r testing}
# 转换为长格式
df_tst <- df_organized %>% 
  select(weekend, value = total_sleep_time) %>% 
  mutate(metric = "Total sleep time")

df_bedtime <- df_organized %>% 
  select(weekend, value = clean_bed_time) %>% 
  mutate(metric = "Bed time")

df_prepare <- df_organized %>% 
  filter(clean_prepare_to_sleep_time < 28) %>% 
  select(weekend, value = clean_prepare_to_sleep_time) %>% 
  mutate(metric = "Prepare to sleep time")

df_wake <- df_organized %>% 
  select(weekend, value = wake_up_time) %>% 
  mutate(metric = "Wake up time")

df_latency <- df_organized %>% 
  filter(sleep_latency < 60) %>% 
  select(weekend, value = sleep_latency) %>% 
  mutate(metric = "Sleep latency")

df_procrastination <- df_organized %>% 
  filter(night_procrastination_time < 2) %>% 
  mutate(value = night_procrastination_time * 60) %>% 
  select(weekend, value) %>% 
  mutate(metric = "Sleep procrastination time")

df_long <- bind_rows(df_tst, df_bedtime, df_prepare, df_wake, df_latency, df_procrastination)

p_combined <- df_long |>
  tidyplot(x = weekend, y = value) |>
  add_boxplot() |>
  add_data_points() |>
  add_test_asterisks(hide_info = TRUE, hide.ns = FALSE) |>
  adjust_x_axis(title = "") |>
  adjust_y_axis(title = "数值") |>
  add_title("周中周末与各项指标的关系") %>%
  adjust_size(width = 100, height = 100) %>% 
  split_plot(by = metric, ncol = 3)

# 显示图表
p_combined

# Bed time，Prepare to sleep time
df_long |> filter(metric %in% c("Bed time", "Prepare to sleep time")) |>
  tidyplot(color = weekend, y = value,x = metric) |>
  add_boxplot() |>
  add_data_points() |>
  add_test_asterisks(hide_info = TRUE, hide.ns = FALSE) |>
  adjust_x_axis(title = "") |>
  adjust_y_axis(title = "时间（小时）") |>
  add_title("周中周末与上床时间和准备睡觉时间的关系") %>%
  adjust_size(width = 100, height = 100)

# 画出sleep latency和sleep procrastination time的箱线图
df_long |> filter(metric %in% c( "Sleep latency", "Sleep procrastination time")) |>
  tidyplot(color = weekend, y = value,x = metric) |>
  add_boxplot() |>
  add_data_points() |>
  add_test_asterisks(hide_info = TRUE, hide.ns = FALSE) |>
  adjust_x_axis(title = "") |>
  adjust_y_axis(title = "时间（分钟）") |>
  adjust_size(width = 100, height = 100)

# 画出total sleep time
df_long |> filter(metric %in% c("Total sleep time")) |>
  tidyplot(color = weekend, y = value,x = metric) |>
  add_boxplot() |>
  add_data_points() |>
  add_test_asterisks(hide_info = TRUE, hide.ns = FALSE) |>
  adjust_x_axis(title = "") |>
  adjust_y_axis(title = "时间（小时）") |>
  add_title("周中周末与总睡眠时长的关系") %>%
  adjust_size(width = 100, height = 100)

# 画出wake up time
df_long |> filter(metric %in% c("Wake up time")) |>
  tidyplot(color = weekend, y = value,x = metric) |>
  add_boxplot() |>
  add_data_points() |>
  add_test_asterisks(hide_info = TRUE, hide.ns = FALSE) |>
  adjust_x_axis(title = "") |>
  adjust_y_axis(title = "时间（小时）") |>
  adjust_size(width = 100, height = 100)


  


```



# 分类变量的占比随时间变化

## 睡眠时长分组百分比
```{r 睡眠时长分组百分比}
## 睡眠时长
# 横轴是日期，纵轴是睡眠时长，画出柱状图，把各个睡眠时长的占比画在一起
temp = df_organized %>% 
  select(term_week_2, total_sleep_time_group, weekend) %>% 
  group_by(term_week_2, total_sleep_time_group) %>% 
  reframe(
    weekend = first(weekend),
    mean_value = n()
  ) %>% 
  mutate(
    total = sum(mean_value),
    proportion = mean_value / total,
    total_sleep_time_group = factor(total_sleep_time_group, levels = rev(c("<6", "[6-7)", "[7-9)", ">9")), ordered = TRUE)
  )

a = ggplot(data = temp, aes(x = term_week_2, y = proportion, fill = total_sleep_time_group)) +
  # 添加标准差阴影（误差带）
  geom_bar(stat = "identity", position = "fill", alpha = 1) +
  
  labs(title = "睡眠时长均值随日期变化", x = "周数", y = "百分比") +
  
  # x轴连续格式
  scale_x_continuous(
    breaks = seq(3, 17, 0.5),
    limits = c(3, 15)
    
  ) +
  # y轴百分比格式
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  
  # fill图例标签
  
  guides(fill = guide_legend(title = "睡眠时长分组")) +
  
  scale_fill_manual(values = rev(c("#FF8080", "#FFC080", "#6AE66A", "#A6A6A6"))) +
  theme_minimal() +
  mytheme

plotly::ggplotly(a)

  
```

## 上床时间分组百分比
```{r 上床时间分组百分比}
# 横轴是日期，纵轴是chronotype，画出柱状图，把各个上床时间的占比画在一起
temp = df_organized %>% 
  select(term_week_2, chronotype, weekend) %>% 
  group_by(term_week_2, chronotype) %>% 
  reframe(
    weekend = first(weekend),
    mean_value = n()
  ) %>% 
  mutate(
    total = sum(mean_value),
    proportion = mean_value / total,
    chronotype = factor(chronotype, levels = rev(c("<23", "[23-24)", "[24-25)", "[25-26)", ">26")), ordered = TRUE)
  )

a = ggplot(data = temp, aes(x = term_week_2, y = proportion, fill = chronotype)) +
  # 添加标准差阴影（误差带）
  geom_bar(stat = "identity", position = "fill", alpha = 1) +
  
  labs(title = "上床时间均值随日期变化", x = "周数", y = "百分比") +
  
  # x轴连续格式
  scale_x_continuous(
    breaks = seq(3, 17, 0.5),
    limits = c(3, 15)
    
  ) +
  # y轴百分比格式
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  
  # fill图例标签
  
  guides(fill = guide_legend(title = "上床时间分组")) +
  theme_minimal() +
  mytheme

plotly::ggplotly(a)
```


